version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=LDAP G3
      - LDAP_DOMAIN=ldap.com
      - LDAP_ADMIN_PASSWORD=12wsa324rwefdgv
      - LDAP_TLS=false  # Disable TLS to avoid connection issues
    ports:
      - "389:389"
      - "636:636"
    command: --copy-service  # Ensures bootstrap files are copied correctly
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false  # Use HTTP to avoid TLS errors
      - PHPLDAPADMIN_LDAP_CLIENT_TLS=false  # Explicitly disable client TLS
    ports:
      - "8080:80"  # Switch to HTTP on port 8080 for easier access
    depends_on:
      - openldap
    restart: unless-stopped