name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify build
      run: |
        echo "Dependencies installed successfully!"
        echo "Build completed successfully!"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/ci-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r ci-requirements.txt

    - name: Create test environment file
      run: |
        cat > app/config/.env << EOF
        APP_NAME=LDAP-FastAPI-Test
        LOG_LEVEL=INFO
        DATABASE_URL=sqlite:///./test.db
        QUEUE_URL=redis://localhost:6379/0
        LDAP_URL=ldap://localhost:389
        LDAP_BIND_DN=cn=admin,dc=example,dc=com
        LDAP_BIND_PASSWORD=admin
        SECRET_KEY=test-secret-key-for-ci
        TOKEN_EXPIRATION=1h
        MONGO_USER=test_user
        MONGO_PASSWORD=test_password
        MONGO_URI=mongodb://localhost:27017
        MONGO_DB_NAME=test_ldap_database
        EOF

    - name: Run tests
      run: |
        python -m pytest tests/ -v

  coverage:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/ci-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r ci-requirements.txt

    - name: Create test environment file
      run: |
        cat > app/config/.env << EOF
        APP_NAME=LDAP-FastAPI-Test
        LOG_LEVEL=INFO
        DATABASE_URL=sqlite:///./test.db
        QUEUE_URL=redis://localhost:6379/0
        LDAP_URL=ldap://localhost:389
        LDAP_BIND_DN=cn=admin,dc=example,dc=com
        LDAP_BIND_PASSWORD=admin
        SECRET_KEY=test-secret-key-for-ci
        TOKEN_EXPIRATION=1h
        MONGO_USER=test_user
        MONGO_PASSWORD=test_password
        MONGO_URI=sqlite:///./test_mongo.db
        MONGO_DB_NAME=test_ldap_database
        EOF

    - name: Run tests with coverage
      run: |
        python -m pytest tests/ -v --cov=app --cov-report=xml --cov-report=html --cov-report=term-missing --ignore=tests/ports/outbound/test_ldap_port.py || true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}